### ISSUE TITLE
Author object should add some fields for request and response

### ISSUE THREAD

**Issue by xius666** [Frieda0315/404#80]
<img width="389" alt="Screen Shot 2021-11-06 at 2 40 04 AM" src="https://user-images.githubusercontent.com/55036290/140603640-2e514488-4893-4013-ac06-9a707e1c85cc.png">
@xichen1

**Comment by xichen1** [comment]
There is no such field [here](https://github.com/abramhindle/CMPUT404-project-socialdistribution/blob/master/project.org#post), why we should add it?

**Comment by xichen1** [comment]
There are two fields that need to be added to Author object: `host` and `profileImage`.
In our case, `host` is always `https://i-connect.herokuapp.com/`,
and by default, the `profileImage` is GitHub avatar. When signing up, it should be set automatically and authors can edit the URL of the avatar later on the profile editing page.

Need to be done first in backend.

**Comment by xichen1** [comment]
finished
