### ISSUE TITLE
Temp dummy posts and comments should be removed

### ISSUE THREAD

**Issue by xichen1** [Frieda0315/404#81]
The tempCommentList and the tempPostList should be removed since the connection between ui and backend is implemented. They are in files PostStream.js and Comment.js.

There is also a tempInbox in Inbox.js, however, it's still in use for some reason. It may also need to be removed after it's connected.

**Comment by xius666** [comment]
> The tempCommentList and the tempPostList should be removed since the connection between ui and backend is implemented. They are in files PostStream.js and Comment.js.
> 
> 
> 
> There is also a tempInbox in Inbox.js, however, it's still in use for some reason. It may also need to be removed after it's connected.

好的

**Comment by xichen1** [comment]
removed
